Repository RotherOSS/otobo, pull requests merged in 2022-12, with the labels that each got.

#2023 Issue #1882: Allow all style options for img tag
  var/httpd/htdocs/js/Core.UI.RichTextEditor.js
Labels: bug

#2024 Issue #2020: Setting class of saving widget similar to the other widg…
  Kernel/Output/HTML/Templates/Standard/AdminACLEdit.tt
Labels: style

#1958 Fixed hidden filters for Medium and Preview
  Kernel/Output/HTML/TicketOverview/Medium.pm
  Kernel/Output/HTML/TicketOverview/Preview.pm
Labels: bug

#2033 Issue #1995 pod of the method table create complex
  Kernel/Output/HTML/LinkObject/Appointment.pm
  Kernel/Output/HTML/LinkObject/Ticket.pm
  bin/otobo.CheckModules.pl
  cpanfile.docker
Labels: documentation, good first issue

#2038 Issue #1996: CSS restructuring
  var/httpd/htdocs/skins/Agent/default/css/Core.Header.css
Labels: style
